version: 1

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
 
build:
  tools:
    python: "3.7"

sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  - epub
